#!/usr/bin/env python3
"""
Generate typed Python bindings from the JSON written by export_webservices.php.

Usage: python codegen/generate.py webservices.json [--output-dir moodle/ws]

This writes the following modules:

- ``types.py`` containing TypedDicts for all (nested) parameters and return values,
- ``methods.py`` containing mixins with one method per webservice function,
  which are inherited by ``MoodleClient`` and ``AsyncMoodleClient``,
- ``__init__.py`` containing information about the Moodle version.

The generated code is formatted using ruff if it is installed.
"""

import argparse
import json
import keyword
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

SUPPORTED_FORMAT_VERSION = 1

# Python types of PARAM_* types. Everything else is a string.
# Note that PARAM_RAW (and few others) technically pass non-string values through unchanged,
# but values from the database are always strings in Moodle.
PARAM_TYPES = {
    "int": "int",
    "float": "float",
    "bool": "bool",
    "localisedfloat": "float | str",
}

# Classes of descriptions whose items are shared between all functions, keyed by the class name.
SHARED_ITEM_TYPES = {
    "external_warnings": "ExternalWarning",
    "external_files": "ExternalFile",
}

HEADER = '''\
"""
{doc}

This file is generated by codegen/generate.py from Moodle {release} - do not edit.
"""
'''


def camel_case(name: str) -> str:
    return "".join(
        part[:1].upper() + part[1:] for part in re.split(r"[^0-9a-zA-Z]+", name)
    )


# Names which are used in methods.py and must thus not be used for arguments.
RESERVED_NAMES = {"self", "TYPE_CHECKING", "cast", "Any", "_types", "_without_none"}


def python_name(name: str) -> str:
    """Return a valid Python identifier for a (keyword) argument."""
    if keyword.iskeyword(name) or name in RESERVED_NAMES:
        return name + "_"
    if not name.isidentifier():
        return "arg_" + re.sub(r"\W", "_", name)
    return name


def clean_text(text: str) -> str:
    """Collapse the (often oddly indented) descriptions into a single line."""
    return " ".join(text.replace("\\\n", " ").split())


def string_literal(text: str) -> str:
    """Return a double quoted string literal, as preferred by ruff format."""
    return json.dumps(text, ensure_ascii=False)


def docstring(text: str, indent: str) -> str:
    text = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if text.endswith('"'):
        text = text[:-1] + '\\"'
    if "\n" not in text:
        return f'{indent}"""{text}"""'
    first, *rest = text.split("\n")
    indented = [f"{indent}{line}" if line else "" for line in rest]
    return "\n".join([f'{indent}"""{first}', *indented, f'{indent}"""'])


def structure_signature(node: dict[str, Any]) -> Any:
    """Return a hashable representation of the type described by a node, ignoring descriptions."""
    if node["kind"] == "value":
        return ("value", node["type"], node["required"], node["allownull"])
    if node["kind"] == "multiple":
        return (
            "multiple",
            structure_signature(node["content"]),
            node["required"],
            node["allownull"],
        )
    keys = tuple(
        (key, structure_signature(child)) for key, child in node["keys"].items()
    )
    return ("single", keys, node["required"], node["allownull"])


@dataclass
class TypesModule:
    """Collects the TypedDicts and type aliases which make up types.py."""

    blocks: list[str] = field(default_factory=list[str])
    names: set[str] = field(default_factory=set[str])
    shared: dict[tuple[str, bool], tuple[Any, str]] = field(
        default_factory=dict[tuple[str, bool], tuple[Any, str]]
    )

    def unique_name(self, name: str) -> str:
        candidate, counter = name, 2
        while candidate in self.names:
            candidate, counter = f"{name}{counter}", counter + 1
        self.names.add(candidate)
        return candidate

    def annotation(
        self, node: dict[str, Any], name: str, returns: bool, in_list: bool = False
    ) -> str:
        """
        Return the annotation for a description, emitting TypedDicts as necessary.

        Parameters cannot be null when sent using the REST protocol,
        so allownull is only honoured for return values.
        """
        if node["kind"] == "value":
            result = PARAM_TYPES.get(node["type"], "str")
        elif node["kind"] == "multiple":
            item_name = name
            if in_list or node.get("class") in SHARED_ITEM_TYPES:
                item_name += "Item"
            item = self.shared_item(node, returns) or self.annotation(
                node["content"], item_name, returns, in_list=True
            )
            result = f"list[{item}]"
        else:
            result = self.typeddict(node, name, returns)

        if returns and node["allownull"]:
            result = f"{result} | None"
        return result

    def shared_item(self, node: dict[str, Any], returns: bool) -> str | None:
        """Reuse a single TypedDict for the items of well-known lists like external_warnings."""
        shared_name = SHARED_ITEM_TYPES.get(node.get("class", ""))
        if shared_name is None:
            return None
        # Parameters and return values are typed differently, so each gets its own TypedDict.
        cache_key = (shared_name, returns)
        signature = structure_signature(node["content"])
        if cache_key not in self.shared:
            name = shared_name if returns else shared_name + "Param"
            self.shared[cache_key] = (
                signature,
                self.typeddict(node["content"], name, returns),
            )
        existing_signature, existing_name = self.shared[cache_key]
        return existing_name if existing_signature == signature else None

    def typeddict(self, node: dict[str, Any], name: str, returns: bool) -> str:
        name = self.unique_name(name)
        fields: list[tuple[str, str, str]] = []
        for key, child in node["keys"].items():
            annotation = self.annotation(child, name + camel_case(key), returns)
            if returns:
                # Missing values with a default are filled in by Moodle, missing structures are not.
                required = child["required"] == "required" or (
                    child["required"] == "default" and child["kind"] == "value"
                )
            else:
                required = child["required"] == "required"
            if not required:
                annotation = f"NotRequired[{annotation}]"
            fields.append((key, annotation, clean_text(child["desc"])))

        if all(
            key.isidentifier() and not keyword.iskeyword(key) for key, _, _ in fields
        ):
            lines = [f"class {name}(TypedDict):"]
            if node["desc"]:
                lines.append(docstring(clean_text(node["desc"]), "    "))
            for key, annotation, desc in fields:
                lines.append(f"    {key}: {annotation}")
                if desc:
                    lines.append(docstring(desc, "    "))
            if len(lines) == 1:
                lines.append("    pass")
        else:
            # Keys which are not valid identifiers require the functional syntax.
            lines = [f"{name} = TypedDict(", f"    {string_literal(name)},", "    {"]
            for key, annotation, _ in fields:
                lines.append(f"        {string_literal(key)}: {annotation},")
            lines += ["    },", ")"]
        self.blocks.append("\n".join(lines))
        return name

    def qualify(self, annotation: str) -> str:
        """Prefix the generated types in an annotation with the module name for use in methods.py."""
        return re.sub(
            r"\b[A-Z]\w*\b",
            lambda match: f"_types.{match[0]}" if match[0] in self.names else match[0],
            annotation,
        )

    def alias(self, name: str, annotation: str) -> str:
        name = self.unique_name(name)
        self.blocks.append(f"{name}: TypeAlias = {annotation}")
        return name

    def render(self, release: str) -> str:
        imports = ["from typing import NotRequired, TypeAlias, TypedDict"]
        doc = "TypedDicts describing the parameters and return values of the Moodle webservice functions."
        header = HEADER.format(doc=doc, release=release) + "\n" + "\n".join(imports)
        return "\n\n\n".join([header, *self.blocks]) + "\n"


@dataclass
class Argument:
    key: str
    """Name of the parameter in Moodle."""
    name: str
    """Name of the keyword argument in Python."""
    declaration: str


@dataclass
class Method:
    arguments: list[Argument]
    returns: str | None
    """Name of the return type in the types module, if the function returns anything."""
    doc: str


def generate_method(name: str, function: dict[str, Any], types: TypesModule) -> Method:
    function_name = camel_case(name)
    arguments: list[Argument] = []
    doc_args: list[str] = []
    for key, child in function["parameters"]["keys"].items():
        annotation = types.qualify(
            types.annotation(
                child, f"{function_name}Params{camel_case(key)}", returns=False
            )
        )
        argument = python_name(key)
        if child["required"] == "required":
            declaration = f"{argument}: {annotation}"
        else:
            declaration = f"{argument}: {annotation} | None = None"
        arguments.append(Argument(key, argument, declaration))

        desc = clean_text(child["desc"]) or "No description."
        if child["required"] == "default":
            desc += f" Defaults to ``{child['default']!r}``."
        doc_args.append(f"{argument}: {desc}")

    returns = None
    if function["returns"] is not None:
        returns = f"{function_name}Returns"
        # A list at the top level has no key to name its items after, so treat it like a nested list.
        annotation = types.annotation(
            function["returns"], returns, returns=True, in_list=True
        )
        if annotation != returns:
            # Lists, scalars, and nullable structures get an alias for consistent naming.
            returns = types.alias(returns, annotation)

    doc = clean_text(function["description"] or "No description.")
    if not doc.endswith("."):
        doc += "."
    if function["deprecated"]:
        doc += "\n\n.. deprecated:: This function is deprecated by Moodle."
    if doc_args:
        doc += "\n\nArgs:\n" + "\n".join(f"    {arg}" for arg in doc_args)
    return Method(arguments, returns, doc)


def render_methods(functions: dict[str, Any], types: TypesModule, release: str) -> str:
    sync_methods: list[str] = []
    async_methods: list[str] = []
    for name, function in functions.items():
        method = generate_method(name, function, types)
        arguments = "self"
        if method.arguments:
            arguments += ", *, " + ", ".join(
                arg.declaration for arg in method.arguments
            )
        data = ", ".join(
            f"{string_literal(arg.key)}: {arg.name}" for arg in method.arguments
        )
        call = f"self.webservice({string_literal(name)}, _without_none({{{data}}}))"
        return_annotation = f"_types.{method.returns}" if method.returns else "None"
        for methods, async_prefix, await_prefix in [
            (sync_methods, "", ""),
            (async_methods, "async ", "await "),
        ]:
            lines = [
                f"    {async_prefix}def {name}({arguments}) -> {return_annotation}:",
                docstring(method.doc, "        "),
            ]
            if method.returns:
                lines.append(
                    f'        return cast("_types.{method.returns}", {await_prefix}{call})'
                )
            else:
                lines.append(f"        {await_prefix}{call}")
            methods.append("\n".join(lines))

    doc = "Mixins providing typed methods for all Moodle webservice functions."
    sync_class = '''\
class WebserviceMethods:
    """Typed methods for all webservice functions, see :class:`moodle.session.MoodleClient`."""

    def webservice(self, wsfunction: str, data: dict[str, Any] | None = None) -> Any:
        raise NotImplementedError'''
    async_class = '''\
class AsyncWebserviceMethods:
    """Typed methods for all webservice functions, see :class:`moodle.session.AsyncMoodleClient`."""

    async def webservice(
        self, wsfunction: str, data: dict[str, Any] | None = None
    ) -> Any:
        raise NotImplementedError'''
    helper = '''\
def _without_none(data: dict[str, Any]) -> dict[str, Any]:
    """Omit arguments which were not passed, so Moodle applies its defaults."""
    return {key: value for key, value in data.items() if value is not None}'''
    classes = [
        "\n\n".join([sync_class, *sync_methods]),
        "\n\n".join([async_class, *async_methods]),
    ]
    # The types module is only imported when type checking,
    # as creating all TypedDicts would noticeably slow down importing pymoodle.
    header = "".join(
        [
            HEADER.format(doc=doc, release=release),
            "\nfrom __future__ import annotations\n\n",
            "from typing import TYPE_CHECKING, Any, cast\n\n",
            "if TYPE_CHECKING:\n    from moodle.ws import types as _types",
        ]
    )
    return "\n\n\n".join([header, helper, *classes]) + "\n"


def render_init(moodle: dict[str, str]) -> str:
    doc = "Typed bindings for the Moodle webservice API."
    constants = [
        f"MOODLE_{key.upper()} = {string_literal(moodle[key])}\n"
        for key in ("version", "release", "branch")
    ]
    return HEADER.format(doc=doc, release=moodle["release"]) + "\n" + "".join(constants)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "input", type=Path, help="JSON file written by export_webservices.php"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "moodle" / "ws",
        help="directory to write the modules to (default: %(default)s)",
    )
    args = parser.parse_args()

    export = json.loads(args.input.read_text(encoding="utf-8"))
    if export.get("format_version") != SUPPORTED_FORMAT_VERSION:
        sys.exit(f"Unsupported format version {export.get('format_version')!r}")
    if export["errors"]:
        print(
            f"Warning: {len(export['errors'])} functions could not be exported and are missing",
            file=sys.stderr,
        )

    release = export["moodle"]["release"]
    types = TypesModule()
    methods = render_methods(export["functions"], types, release)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "__init__.py": render_init(export["moodle"]),
        "types.py": types.render(release),
        "methods.py": methods,
    }
    for filename, content in files.items():
        (args.output_dir / filename).write_text(content, encoding="utf-8")

    paths = [str(args.output_dir / filename) for filename in files]
    for command in (["check", "--fix-only", "--quiet"], ["format", "--quiet"]):
        try:
            subprocess.run([sys.executable, "-m", "ruff", *command, *paths], check=True)
        except subprocess.CalledProcessError:
            print(f"Warning: running ruff {command[0]} failed", file=sys.stderr)

    print(
        f"Generated bindings for {len(export['functions'])} functions of Moodle {release} in {args.output_dir}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
