"""
Typed bindings for the Moodle webservice API.

This file is generated by codegen/generate.py from Moodle 4.5.14+ (Build: 20261002) - do not edit.
"""

MOODLE_VERSION = "2024100714.03"
MOODLE_RELEASE = "4.5.14+ (Build: 20261002)"
MOODLE_BRANCH = "405"
